name: MicroProfile Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
    - name: Build distorm
      run: |
        export DISTORM_MODE=DISTORM_STATIC
        pushd distorm/make/linux
        make
        popd
    - name : Build demo_simple
      run: |
        pushd demo/simple
        make clean
        make
        popd
    - name : Build demo_c
      run: |
        pushd demo/c
        make clean
        make
        popd
    - name : Build demo_workbench
      run: |
        pushd demo/workbench
        make clean
        make
        popd
    - name : Build demo_noframes
      run: |
        pushd demo/noframes
        make clean
        make
        popd
    - name : test demo_noframes
      run: |
        pushd demo/noframes
        ./noframes
        popd

        

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
    - name: Build distorm
      run: |
        export DISTORM_MODE=DISTORM_STATIC
        pushd distorm/make/mac
        make
        popd
    - name : Build demo_simple
      run: |
        pushd demo/simple
        make
        popd
    - name : Build demo_workbench
      run: |
        pushd demo/workbench
        make
        popd
    - name : Build demo_c
      run: |
        pushd demo/c
        make
        popd
    - name : Build demo_noframes
      run: |
        pushd demo/noframes
        make
        popd
    - name : test demo_noframes
      run: |
        pushd demo/noframes
        ./noframes
        popd

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64
      - name: Checkout submodules
        run: |
          git submodule update --init --recursive
      - name: build distorm
        run: |
          pushd distorm\\make\\win32\\
          MSBuild.exe cdistorm.vcxproj /property:Configuration='clib'
          popd
      - name: build demo_simple
        run: |
          pushd demo\\simple\\
          MSBuild.exe simple.vcxproj /property:Configuration='Release'
          MSBuild.exe simple.vcxproj /property:Configuration='Debug'
          popd
      - name: build demo_workbench
        run: |
          pushd demo\\workbench\\
          MSBuild.exe workbench.vcxproj /property:Configuration='Release'
          MSBuild.exe workbench.vcxproj /property:Configuration='Debug'
          popd
      - name: build demo_c
        run: |
          pushd demo\\c\\
          MSBuild.exe c.vcxproj /property:Configuration='Release'
          MSBuild.exe c.vcxproj /property:Configuration='Debug'
          popd
      - name: build demo_noframes
        run: |
          pushd demo\\noframes\\
          MSBuild.exe noframes.vcxproj /property:Configuration='Release'
          MSBuild.exe noframes.vcxproj /property:Configuration='Debug'
          dir 
          dir x64
          dir x64\\Debug
          popd
      - name: test demo_noframes
        run: |
          pushd demo\\noframes\\
          x64\\Debug\\noframes
          x64\\Release\\noframes
          popd

